apiVersion: v1
kind: Pod
metadata:
  name: vault
  labels:
    app: HashiCorpVault
    tier: frontend
spec:
  containers:
    - name: vault
      image: vault
      ports:
        - containerPort: 8200
